### ISSUE TITLE
Broken interface on 4:3 monitor

### ISSUE THREAD

**Issue by Damienov** [parsimony/parsimony#68] opened 2014-03-01 07:22 UTC
UI is broken when viewed on a 4:3 ratio monitor
![screenshot from 2014-03-01 14 18 58](https://f.cloud.github.com/assets/3100358/2300885/3491d90e-a112-11e3-9c26-948404247cdc.png)

**Comment by parsimony** [comment] 2014-03-03 09:01
We can't reproduce this bug, can you tell us with which browser ?

**Comment by Damienov** [comment] 2014-03-03 12:41
Firefox 21.0
Ubuntu 13.10
Monitor resolution 1280x1024 (minus about 48px of width because of the Ubuntu sidebar)

Also tested in:
Chromium - Version 25.0.1364.160 Built on Ubuntu 13.04, running on Ubuntu 13.10 (25.0.1364.160-0ubuntu3)
the open source version of Chrome, with the same result. The top menu overlap
<a href="http://imgur.com/TrmPgVS"><img src="http://i.imgur.com/TrmPgVS.png" title="Hosted by imgur.com" /></a>

**Comment by parsimony** [comment] 2014-03-03 13:18
Ok , it's because you have old versions of firefox and chrome, please update them.
Parsimony admin menu uses flexboxs, which requires firefox 22 or chrome 29 ( https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes#Browser_compatibility )

**Comment by Damienov** [comment] 2014-03-03 21:06
Tested in Firefox 27 and Chromium 32.0.1700.107 Ubuntu 13.10 working great. Perhaps adding a warning about browser version in the docs?

That said, it seems the dbDesigner shows double field and that makes few of the field not showing/unscrollable in smaller monitor (img below).

<a href="http://imgur.com/LpqZIO6"><img src="http://i.imgur.com/LpqZIO6.png" title="Hosted by imgur.com" /></a>

**Comment by parsimony** [comment] 2014-03-04 09:35
Thanks for this feedback, it's now fixed ( https://github.com/parsimony/parsimony/commit/3a12d98c447fa8aaf71f89c3231a21d560a26da3 ), it was due to an old PHP bug (https://bugs.php.net/bug.php?id=62343)

**Closed as completed** 2014-03-04 11:25 UTC
